CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255),
	pass VARCHAR(255),
	image_url VARCHAR(255),
	keycode VARCHAR(255) NOT NULL,
	expiry_date INT NOT NULL
);

CREATE TABLE posts (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	parent_id INT,
	date BIGINT NOT NULL,
	image_url VARCHAR(255),
	content VARCHAR(255),
	subject VARCHAR(255)
);
